CONTIKI_PROJECT = tarea3
#CONTIKI_SOURCEFILES += gpioc3.c
ifndef TARGET
	TARGET=zoul
endif
all: $(CONTIKI_PROJECT)

CONTIKI = /home/user/contiki
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include

